### ISSUE TITLE
Add deb, rpm and snap packages to releases

### ISSUE THREAD

**Issue by nikoksr** [nikoksr/proji#114]
**Is your feature request related to a problem? Please describe.**
We should add [deb](https://wiki.debian.org/deb), [rpm](https://en.wikipedia.org/wiki/RPM_Package_Manager) and [snap](https://snapcraft.io/) packages to our release list. Many people use [Debian](https://www.debian.org/), [Debian derivatives](https://www.debian.org/derivatives/) like [Ubuntu](https://ubuntu.com/) or [RedHat](https://www.redhat.com/en) and its derivatives like [Fedora](https://getfedora.org/). And almost every modern Linux distro supports the installation of software packages with `snap`. 

We should include these packages to our release list to make the installation of proji for many people a little easier.

**Describe the solution you'd like**
Proji uses [goreleaser](https://goreleaser.com/) to manage its releases automatically. And goreleaser  happens to support the release of deb, rpm and snap packages (see [here](https://goreleaser.com/customization/#NFPM) and [here](https://goreleaser.com/customization/#Snapcraft)). 

Our goreleaser config should be extended and include the necessary settings for said packages.

**Additional context**
The config must be tested before adding it on the master branch. [Goreleaser quick-start guide](https://goreleaser.com/quick-start/) contains instructions on how to test-run the config locally before publishing it.

**Comment by ssivaguru** [comment]
i would like to work on this

**Comment by nikoksr** [comment]
@ssivaguru sure, go ahead!

**Comment by nikoksr** [comment]
Closed in 0bacb9850c0c9be8e70fe8bb7822b869f743dbc7.
