### ISSUE TITLE
Improve package editing

### ISSUE THREAD

**Issue by nikoksr** [nikoksr/proji#137]
**Is your feature request related to a problem? Please describe.**
At this point in time if you want to edit an existing package, you have to export it, open its config in your favorite text editor, edit the config, save it; and in the case that you actually want to replace the old package config with the new one, you have to remove the old package and import the new one manually. 
It sounds worse than it actually is, yet still it's quite a lot to do for a simple task.

**Describe the solution you'd like**
A simpler approach would be to add something like a subcommand `proji package edit LABEL` and let proji automatically open the config file in your favorite text editor. Proji would copy the original config to a temp or cache folder, open this copy for editing and check for changes, if the file has changed, ask the user if he wants to replace the old config with it.

**Additional context**
Obviously that would make the editing process more enjoyable but there a lot of things which might not really work out as planned. I guess I'll implement it for tryouts and we'll see.

**Comment by nikoksr** [comment]
See [skratchdot/open-golang](https://github.com/skratchdot/open-golang).

**Comment by nikoksr** [comment]
A first version of this feature can be found [here](https://github.com/nikoksr/proji/tree/improve-package-editing).

Need feedback if the automatic opening of config files works on different platforms:
- [x] Linux
- [ ] MacOS
- [ ] Windows

**Comment by FelixMohr** [comment]
Hi @nikoksr,

I've checked it on MacOS and unfortunately got an error.
![Screenshot 2020-11-29 at 15 41 58](https://user-images.githubusercontent.com/6664128/100544938-73ba4f00-3259-11eb-8356-f33af8f69d77.png)

The reason is that on my machine, no application is connected to TOML files:
![Screenshot 2020-11-29 at 15 41 10](https://user-images.githubusercontent.com/6664128/100544974-9a788580-3259-11eb-880b-fed073dfec87.png)

I think this might apply to many users. A possible solution for MacOS might be to try open.Run first. If an error on MacOS occurs, instead, ``open.RunWith(configFile, "TextEdit")`` could be executed. TextEdit is a simple text editor that's available on any Mac.

**Comment by nikoksr** [comment]
@FelixMohr I implemented your recommended changes. When the `open` command fails to automatically open the config in a text editor it will try to open the file with the program `TextEdit`. 

Would be highly appreciated if you could test the changes on the [improve-package-editing](https://github.com/nikoksr/proji/tree/improve-package-editing) branch for macOS.

**Comment by FelixMohr** [comment]
Sure :) 

<img width="1230" alt="Screenshot 2020-12-08 at 19 08 06" src="https://user-images.githubusercontent.com/6664128/101523718-3e181300-3989-11eb-865b-2ff88b4491b0.png">

Works exactly as intended:

- No application has been chosen for opening TOML files: `proji package edit` opens the configuration with TextEdit (Screenshot). After saving and pressing Enter, the new config is persisted.
- After specifying an application (VS Code) to be used for opening TOML files, `proji package edit` opens the file in VS Code. Updates are persisted successfully.

**Comment by nikoksr** [comment]
Check package editing under Windows and it opened the dialog for choosing a default application for `toml` files immediately so I'll let that one pass working.
