### ISSUE TITLE
Completion for imports

### ISSUE THREAD

**Issue by nikoksr** [nikoksr/proji#55]
`proji class import` doesn't auto-complete the file system when [tab-completion](https://github.com/nikoksr/proji#tab-completion-) is enabled. Paths and file names have to be entered manually.

**Comment by sagis-tikal** [comment]
Depends on which shell you are using - I'm using fish and seems like the completion is working flawlessly.
It might be best to create a completion script for both zsh and bash though.

**Comment by nikoksr** [comment]
You're totally right. I didn't express myself clear enough. The issue with proji not completing the file system only occurs for me when I enable the [tab-completion](https://github.com/nikoksr/proji#tab-completion-) of my shell for proji.

**Comment by sagis-tikal** [comment]
👍
