### ISSUE TITLE
Broken link “proji-class-example.toml” in the README

### ISSUE THREAD

**Issue by roryokane** [nikoksr/proji#61]
[README.md](https://github.com/nikoksr/proji/blob/develop/README.md) includes this link:

~~~markdown
Proji creates the file [proji-class-example.toml](configs/example-class-export.toml) in the current working directory.
~~~

When rendered on GitHub, [proji-class-example.toml](https://github.com/nikoksr/proji/blob/develop/configs/example-class-export.toml) links to https://github.com/nikoksr/proji/blob/develop/configs/example-class-export.toml, which doesn’t exist.

Maybe that file became one of TOML files in [`assets/examples/`](https://github.com/nikoksr/proji/tree/develop/assets/examples), such as [`assets/examples/example-config.toml`](https://github.com/nikoksr/proji/blob/develop/assets/examples/example-config.toml)?

**Comment by nikoksr** [comment]
Confirmed. Thanks for the report.
