### ISSUE TITLE
A collection/repository of classes

### ISSUE THREAD

**Issue by sagis-tikal** [nikoksr/proji#63]
I think the project and the community would highly appreciate a community based repository or collection for useful generic classes - one for each language as a start.
I would've started but I've it to create any classes.

**Comment by nikoksr** [comment]
I totally agree. A collection of classes would probably help a lot of people.

What I would find even cooler would be if we implemented commands to push and pull classes, similar to `git` and `docker`.

**Comment by sagis-tikal** [comment]
That's an amazing idea!

**Comment by nikoksr** [comment]
I created a [repo](https://github.com/nikoksr/proji-templates) which lets us store configs, templates and scripts for now. But as readable in the readme, it is by far not the final solution. I just wanted to mention the creation of the repo.

**Comment by nikoksr** [comment]
Closing for now. [proji-examples](https://github.com/nikoksr/proji-examples) will be the config collection until a better alternative is found.

**Comment by nikoksr** [comment]
[proji-examples](https://github.com/nikoksr/proji-examples) will be replaced by proji packages and collections, coming with version 0.20.0.

See #113 for more informations.

**Comment by nikoksr** [comment]
Moved to #113
