### ISSUE TITLE
Add json support

### ISSUE THREAD

**Issue by nikoksr** [nikoksr/proji#80]
**Is your feature request related to a problem? Please describe.**
Proji currently only supports `TOML` as config file format. Since it's quite possible that proji will work with APIs in the future (#63), you should be able to export/import configs in `JSON` format as well.

**Describe the solution you'd like**
Add a flag to package related commands. `TOML` might stay the default format for configs but you could export configs to `JSON` with a `--to-json` flag or similar.

This is just an example solution. Other solutions are of course open for discussion!

**Comment by nikoksr** [comment]
#63

**Comment by nikoksr** [comment]
Related to #63

**Comment by georgettica** [comment]
attempting to help with merging this.. let me know if I can take ownership
