### ISSUE TITLE
Add 'stdin' and 'stdout' flags to 'import' and 'export' commands

### ISSUE THREAD

**Issue by nikoksr** [nikoksr/proji#91]
**Is your feature request related to a problem? Please describe.**
Class configs should be im- and exportable via [stdin](https://en.wikipedia.org/wiki/Standard_streams#Standard_input_(stdin)) and [stdout](https://en.wikipedia.org/wiki/Standard_streams#Standard_output_(stdout)). It should push raw TOML configs into stdout and accept raw TOML configs from stdin.

**Describe the solution you'd like**
The flags should work and be implemented similarly to the [other import flags](https://github.com/nikoksr/proji/blob/master/cmd/proji/cmd/classImport.go) (config, directory, remote-repo). 

**Example**
```bash
proji class import --stdin <raw class config here>
proji class export --stdout <class label>
```

**Comment by FearFactor3** [comment]
I'm interested in working on this.
